In [7]:
import torch
import numpy as np

# 1. Matrices

- Tensors (PyTorch)
- Ndarrays (Numpy)

### 1.1 Creating Matrices

In [4]:
arr = [[1, 2], [3, 4]]
print(arr)

[[1, 2], [3, 4]]


In [5]:
np.array(arr)

array([[1, 2],
       [3, 4]])

In [8]:
torch.Tensor(arr)

tensor([[1., 2.],
        [3., 4.]])

### 1.2 Creating Matrices with Default Values

In [10]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [11]:
torch.ones((2, 3))

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [12]:
np.random.rand(2, 2)

array([[0.1095947 , 0.86723519],
       [0.86411053, 0.70964577]])

In [13]:
torch.rand(2, 2)

tensor([[0.2783, 0.6606],
        [0.4350, 0.5586]])

### 1.3 Seeds for Reproducibility

In [14]:
np.random.seed(0)
np.random.rand(3, 2)

array([[0.5488135 , 0.71518937],
       [0.60276338, 0.54488318],
       [0.4236548 , 0.64589411]])

In [15]:
np.random.seed(0)
np.random.rand(3, 2)

array([[0.5488135 , 0.71518937],
       [0.60276338, 0.54488318],
       [0.4236548 , 0.64589411]])

In [16]:
np.random.rand(3, 2)

array([[0.43758721, 0.891773  ],
       [0.96366276, 0.38344152],
       [0.79172504, 0.52889492]])

In [17]:
torch.manual_seed(0)
torch.rand(2, 3)

tensor([[0.4963, 0.7682, 0.0885],
        [0.1320, 0.3074, 0.6341]])

In [18]:
torch.manual_seed(0)
torch.rand(2, 3)

tensor([[0.4963, 0.7682, 0.0885],
        [0.1320, 0.3074, 0.6341]])

In [19]:
torch.rand(2, 3)

tensor([[0.4901, 0.8964, 0.4556],
        [0.6323, 0.3489, 0.4017]])

### 1.4 NumPy and Torch Bridge

#### NumPy to Torch

In [21]:
np_arr = np.ones((3, 4))
print(np_arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [22]:
print(type(np_arr))

<class 'numpy.ndarray'>


In [24]:
torch_tensor = torch.from_numpy(np_arr)
print(torch_tensor)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)


In [25]:
print(type(torch_tensor))

<class 'torch.Tensor'>


#### Data type problem

In [31]:
np_arr = np.ones((3, 4), dtype=np.uint16)
torch.from_numpy(np_arr)

TypeError: can't convert np.ndarray of type numpy.uint16. The only supported types are: float64, float32, float16, int64, int32, int16, int8, and uint8.

In [32]:
np_arr = np.ones((3, 4), dtype=np.int8)
torch.from_numpy(np_arr)

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=torch.int8)

#### Torch to NumPy

In [34]:
torch_tensor = torch.ones((3, 2))
type(torch_tensor)

torch.Tensor

In [35]:
np_arr = torch_tensor.numpy()
type(np_arr)

numpy.ndarray

### 1.5 Tensor Operations

#### Resizing Tensor

In [37]:
a = torch.ones(3, 2)
print(a.size())

torch.Size([3, 2])


In [42]:
a.view(6)

tensor([1., 1., 1., 1., 1., 1.])

In [43]:
a.view(6).size()

torch.Size([6])

#### Element-wise Addition Subtraction

In [44]:
a = torch.ones(3, 2)
print(a)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


In [45]:
b = torch.ones(3, 2)
print(b)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


In [46]:
a + b

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])

In [49]:
c=torch.add(a, b)
print(c)

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])


In [54]:
c.add(a)
print(c)

tensor([[4., 4.],
        [4., 4.],
        [4., 4.]])


In [55]:
# Inplace
c.add_(a)
print(c)

tensor([[5., 5.],
        [5., 5.],
        [5., 5.]])


In [57]:
c.sub(a)
print(c)

tensor([[5., 5.],
        [5., 5.],
        [5., 5.]])


In [58]:
# Inplace
c.sub_(a)
print(c)

tensor([[4., 4.],
        [4., 4.],
        [4., 4.]])


#### Element-wise Multiplication Division

In [59]:
print(a.mul_(b))

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


In [60]:
b=torch.zeros((3, 2))
print(b.div_(a))

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])


#### Tensor mean

In [61]:
a = torch.Tensor([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
a.size()

torch.Size([10])

In [62]:
a.mean(dim=0)

tensor(5.5000)

In [63]:
a.mean(dim=1)

IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

In [66]:
a = torch.Tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]])
a.size()

torch.Size([2, 10])

In [67]:
a.mean()

tensor(5.5000)

In [68]:
a.mean(dim=0)

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [69]:
a.mean(dim=1)

tensor([5.5000, 5.5000])

#### Torch Standard Deviation

In [72]:
a = torch.Tensor([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
a.std()

tensor(3.0277)